package com.nracademy.backend.entity.enums;

public enum StatusCode {
    USER_NOT_FOUND,
    USER_EMAIL_NOT_FOUND,
    ROLE_NOT_FOUND,
    EMAIL_ALREADY_REGISTERED,
    STORAGE_UPLOAD_FAILED,
    STORAGE_DELETE_FAILED,
    MISSING_REQUIRED_FIELD,
    UNSUPPORTED_MEDIA_TYPE,
    VALIDATION_FAILED,
    UNAUTHENTICATED,

    PASSWORD_MISMATCH,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED,
    INVALID_CURRENT_PASSWORD,

    // --- Pagination / sorting ---
    INVALID_PAGINATION_PARAMETERS,
    PAGE_SIZE_EXCEEDED,
    UNSUPPORTED_SORT_FIELD,
    UNSUPPORTED_SORT_DIRECTION,

    // --- Search / filtering ---
    SEARCH_QUERY_TOO_SHORT,
    INVALID_SEARCH_QUERY,
    UNSUPPORTED_SEARCH_FIELD,
    UNSUPPORTED_FILTER,
    INVALID_FILTER_VALUE,
    FILTER_COMBINATION_NOT_ALLOWED,
    INVALID_DATE_RANGE,

    // --- General request validation ---
    INVALID_UUID,
    INVALID_ENUM_VALUE,
    INVALID_REQUEST_BODY,

    // --- Authorization / tenant / status ---
    ACCESS_DENIED,
    ROLE_FORBIDDEN,
    TENANT_ACCESS_DENIED,
    COURSE_INACTIVE,
    COURSE_BLOCKED,
    USER_INACTIVE,
    USER_BLOCKED,

    // --- Fallback for uncategorized DB-level failures ---
    DATA_INTEGRITY_VIOLATION,

    // --- Course ---
    COURSE_NOT_FOUND,
    DUPLICATE_COURSE_NAME,
    INVALID_COMMISSION_RATE,
    INVALID_PAYMENT_PER_STUDENT,

    // --- User admin ---
    INVALID_ROLE,
}
