package com.nracademy.backend.entity.enums;

public enum StatusCode {
    USER_NOT_FOUND,
    USER_EMAIL_NOT_FOUND,
    ROLE_NOT_FOUND,
    EMAIL_ALREADY_REGISTERED,
    STORAGE_UPLOAD_FAILED,
    STORAGE_DELETE_FAILED,
    MISSING_REQUIRED_FIELD,
    UNSUPPORTED_MEDIA_TYPE,
    VALIDATION_FAILED,
    UNAUTHENTICATED,

    PASSWORD_MISMATCH,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED,
    INVALID_CURRENT_PASSWORD,

    // --- Pagination / sorting ---
    INVALID_PAGINATION_PARAMETERS,
    PAGE_SIZE_EXCEEDED,
    UNSUPPORTED_SORT_FIELD,
    UNSUPPORTED_SORT_DIRECTION,

    // --- Search / filtering ---
    SEARCH_QUERY_TOO_SHORT,
    INVALID_SEARCH_QUERY,
    UNSUPPORTED_SEARCH_FIELD,
    UNSUPPORTED_FILTER,
    INVALID_FILTER_VALUE,
    FILTER_COMBINATION_NOT_ALLOWED,
    INVALID_DATE_RANGE,

    // --- General request validation ---
    INVALID_UUID,
    INVALID_ENUM_VALUE,
    INVALID_REQUEST_BODY,

    // --- Authorization / tenant / status ---
    ACCESS_DENIED,
    ROLE_FORBIDDEN,
    TENANT_ACCESS_DENIED,
    COURSE_INACTIVE,
    COURSE_BLOCKED,
    USER_INACTIVE,
    USER_BLOCKED,

    // --- Fallback for uncategorized DB-level failures ---
    DATA_INTEGRITY_VIOLATION,

    // --- Course ---
    COURSE_NOT_FOUND,
    DUPLICATE_COURSE_NAME,
    INVALID_COMMISSION_RATE,
    INVALID_PAYMENT_PER_STUDENT,

    // --- User admin ---
    INVALID_ROLE,

    // --- Quiz ---
    QUIZ_ERROR,
    QUIZ_ATTEMPT_ERROR,
    QUIZ_NOT_FOUND,
    QUIZ_NOT_PUBLISHED,
    QUIZ_NOT_AVAILABLE,
    QUIZ_NOT_ASSIGNED_TO_GROUP,
    QUIZ_NOT_ASSIGNED_TO_STUDENT,
    QUIZ_STATUS_TRANSITION_INVALID,
    QUIZ_QUESTION_NOT_FOUND,
    QUIZ_QUESTION_HAS_NO_CORRECT_OPTION,
    QUIZ_QUESTION_OPTION_NOT_FOUND,
    QUIZ_CORRECT_OPTION_EXPOSED,
    QUIZ_DURATION_INVALID,
    QUIZ_ATTEMPT_LIMIT_EXCEEDED,
    QUIZ_ATTEMPT_NOT_FOUND,
    QUIZ_ATTEMPT_ALREADY_STARTED,
    QUIZ_ATTEMPT_ALREADY_SUBMITTED,
    QUIZ_ATTEMPT_EXPIRED,
    QUIZ_ATTEMPT_NOT_IN_PROGRESS,
    QUIZ_ANSWER_INVALID,
    QUIZ_ANSWER_QUESTION_MISMATCH,
    QUIZ_AUTO_COMPLETION_FAILED,
    QUIZ_GRADING_FAILED,
}
