package com.nracademy.backend.entity.enums;

public enum StatusCode {
    USER_NOT_FOUND,
    USER_EMAIL_NOT_FOUND,
    ROLE_NOT_FOUND,
    EMAIL_ALREADY_REGISTERED,
    STORAGE_UPLOAD_FAILED,
    STORAGE_DELETE_FAILED,
    MISSING_REQUIRED_FIELD,
    UNSUPPORTED_MEDIA_TYPE,
    VALIDATION_FAILED,
    UNAUTHENTICATED,
}
